### PR TITLE
Adds support for displaying an icon by using the src attribute

### PR DESCRIPTION
**Pull request by brunovianarezende**
this is useful when we want the icon to be an image instead of a VaadinIcon

### CODE REVIEW

**Comment by brunovianarezende** [comment]
> I would assume that icon source provider is alternative approach of giving icon if you do not use icon from VaadinIcon. Thus I would assume we do not need API where both are given at the same time.

actually, my use case requires that I provide in some entries a VaadinIcon and in others an image  as the icon.

**Comment by brunovianarezende** [comment]
if IronIcon exposed the `src` attribute that the `iron-icon` tag accepts, we could have just a ironIconProvider and we could construct the tag based on it. But, unforturnately, it doesn't. It would also allow the icon to be from a different family than `vaadin:`.

**Comment by TatuLund** [comment]
Please add

```
public Column<T> setHierarchyColumn(ValueProvider<T, ?> valueProvider, ValueProvider<T, VaadinIcon> iconProvider, ValueProvider<T, String> titleProvider) {
    setHierarchyColumn(valueProvider, iconProvider, null, titleProvider) 
} 
```

For backwards compatibility, also have you verified that null is allowed for iconSrcProvider ?

**Comment by brunovianarezende** [comment]
ok, I will add that. I tried to add checks in the code for when iconSrcProvider is null, but I will add something in View.java to be 100% sure.

**Comment by brunovianarezende** [comment]
@TatuLund : the method was added back and I made sure the component works without `iconSrcProvider`. I've also added some code to unregister the StreamResources that were registered (https://vaadin.com/api/platform/20.0.7/com/vaadin/flow/server/StreamResourceRegistry.html#registerResource-com.vaadin.flow.server.AbstractStreamResource-).

**Comment by TatuLund** [comment]
>  I've also added some code to unregister the StreamResources that were registered

@brunovianarezende Excellent

**Pull request merged**
